language: node_js
node_js:
  - 12.13.1
cache: npm

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: npm
  skip_cleanup: true
  email: "dinaghalini@gmail.com"
  api_key: $NPM_TOKEN
  local_dir: dist
  on:
    branch: master
